version: '3'

services:
  web:
    build: ~/DevopsApplication/DevOps/DockerApplication/
    ports:
      - "8080:8080"
  mysql:
    image: mysql:latest
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=D@cker1234
    volumes:
      - mysql-db-data:/var/lib/mysql

volumes:
  mysql-db-data:
